# 操作系统
os:
  - "linux"
# 编程语言
language: node_js
# 语言版本
node_js:
  - "10"
  - "8"
  - "6"
# 环境变量
env:
  matrix:
  - PROJECT_VERSION="1.0.*"

# 需要插件
addons:
  chrome: stable

  # 设置脚本
before_install:
  - echo "now is in before_install Phase"
  - echo $PROJECT_VERSION
  # feat:集成测试
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - echo "now is in install Phase"
  - npm install
before_script:
  - echo "now is in before_script Phase"
script:
  - echo "now is in script Phase"
  - npm run test:e2e
after_success:
  - echo "now is in after_success Phase"
after_failure:
  - echo "now is in after_failure Phase"
before_deploy:
  - echo "now is in before_deploy Phase"
  - "echo 'ready?'"

# 缓存依赖
cache: npm